config/routes.rb
Rails.application.routes.draw do
  resources :orders
  root "store#index"
  get 'store/index'

  resources :line_items, only: [:create, :destroy]
  resource :basket, only: [:destroy]
  resources :promotions, only: [:create, :destroy]
end

app/views/shared/_basket.html.erb
<div class="card">
  <div class="card-body">
    <h4 class="card-title">Your Basket</h4>

    <%= render partial: 'shared/line_items', locals: { subject: basket, delete_links: true } %>

    <%= form_with(url: promotions_path, method: :post, class: "mb-3") do |f| %>
      <%= f.label :code, "Promo Code" %>
      <%= f.text_field :code %>
      <%= f.submit "Apply", class: "btn btn-info btn-sm" %>
    <% end %>

    <%= link_to "Checkout", new_order_path, class: "btn btn-warning" %>
    <%= link_to "Delete Basket", basket_path, data: { turbo_method: :delete }, class: "btn btn-danger" %>
  </div>
</div>

app/views/shared/_line_items.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Price per unit</th>
      <th>Total Price</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% subject.line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.name %></td>
        <td><%= line_item.quantity %></td>
        <td><%= line_item.price_per_unit %></td>
        <td><%= line_item.total_price %></td>
        <td>
          <% if delete_links %>
            <%= link_to line_item, class: "btn btn-danger btn-sm", data: { turbo_method: :delete } do %>
              <i class="bi-trash"></i>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <tr>
      <th colspan="3">Total Before Promotions</th>
      <td colspan="2">
        <%= subject.total_before_promotions %>
      </td>
    </tr>

    <% if subject.promotion_codes.any? %>
      <tr>
        <th colspan="5">Promotions</th>
      </tr>
    <% end %>
    <% subject.promotion_codes.each do |promo_code| %>
      <tr>
        <td colspan="3">
          <%= promo_code.name %>
          <%= tag.span "exclusive", class: 'badge bg-info' unless promo_code.can_combine? %>
          </th>
          <td>
            <%= promo_code.apply_to(subject.total_before_promotions).round(2) %>
          </td>
          <td>
            <% if delete_links %>
              <%= link_to promotion_path(promo_code), class: "btn btn-danger btn-sm", data: { turbo_method: :delete } do %>
                <i class="bi-trash"></i>
              <% end %>
            <% end %>
          </td>
      </tr>
    <% end %>
    <tr>
      <th colspan="3">Total</th>
      <td colspan="2">
        <%= subject.total %>
      </td>
    </tr>
  </tbody>
</table>