config/routes.rb
Rails.application.routes.draw do
  resources :orders
  root "store#index"
  get 'store/index'

  resources :line_items, only: [:create, :destroy]
  resource :basket, only: [:destroy]
  resources :promotions, only: [:create, :destroy]
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_orders_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Order < ApplicationRecord
  include PriceCalculation

  belongs_to :user
  has_many :line_items
  has_and_belongs_to_many :promotion_codes

  def transfer_line_items_and_promotions_from_basket(basket)
    basket.line_items.each do |line_item|
      line_item.basket_id = nil
      line_items << line_item
    end

    basket.promotion_codes.each do |promo_code|
      promotion_codes << promo_code
    end

    save
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :ensure_basket_present, only: [:new, :create]
  before_action :set_order, only: [:show]

  # GET /orders/new
  def new
    @user = User.new
    @user.build_address
    @user.build_credit_card
  end

  # POST /orders or /orders.json
  def create
    @user = User.new(user_params)

    if @user.save
      order = Order.create(user: @user)
      set_current_basket
      order.transfer_line_items_and_promotions_from_basket(@current_basket)

      @current_basket.reload # avoid deleting transfered line items & promotions
      delete_current_basket

      redirect_to order_url(order), notice: "Order was successfully created."
    else
      logger.debug @user.errors.details
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  private

    def user_params
      params.require(:user).permit(:email,
                                   address_attributes: [:city, :country, :line1, :line2],
                                   credit_card_attributes: [:number, :expiry_date, :cvv2]
                                  )
    end

    def set_order
      @order = Order.find(params[:id])
    end

    def ensure_basket_present
      redirect_to root_url, notice: "Please add items to cart before you place an order" unless basket_present?
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: user, url: orders_path, method: :post) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red" class="mb-3">
      <h5>Please correct errors bellow</h5>
    </div>
  <% end %>

  <fieldset>
    <legend>Info</legend>
    <div class="mb-3 row">
      <%= form.label :email, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= form.text_field :email, class: 'form-control' %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Address</legend>
    <%= form.fields_for(:address) do |address_form| %>

      <div class="mb-3 row">
        <%= address_form.label :country, class: 'col-sm-2 col-form-label' %>
        <div class="col-sm-10">
          <%= address_form.text_field :country, class: 'form-control' %>
        </div>
      </div>

      <div class="mb-3 row">
        <%= address_form.label :city, class: 'col-sm-2 col-form-label' %>
        <div class="col-sm-10">
          <%= address_form.text_field :city, class: 'form-control' %>
        </div>
      </div>

      <div class="mb-3 row">
        <%= address_form.label :line1, "Line 1", class: 'col-sm-2 col-form-label' %>
        <div class="col-sm-10">
          <%= address_form.text_field :line1, class: 'form-control' %>
        </div>
      </div>

      <div class="mb-3 row">
        <%= address_form.label :line2, "Line 2", class: 'col-sm-2 col-form-label' %>
        <div class="col-sm-10">
          <%= address_form.text_field :line2, class: 'form-control' %>
        </div>
      </div>

    <% end %>
  </fieldset>

  <fieldset>
    <legend>Credit Card</legend>
    <%= form.fields_for(:credit_card) do |credit_card_form| %>

      <div class="row">
        <%= credit_card_form.label :number, class: 'col-sm-2 col-form-label' %>
        <div class="col-sm-10">
          <%= credit_card_form.text_field :number, class: 'form-control' %>
        </div>
      </div>
      <div class="mb-3 row justify-content-end">
        <div class="col-sm-10">
          <div class="form-text">
            Must be in format 1234 5678
          </div>
        </div>
      </div>

      <div class="mb-3 row">
        <%= credit_card_form.label :expiry_date, class: 'col-sm-2 col-form-label' %>
        <div class="col-sm-10">
          <%= credit_card_form.date_select :expiry_date, 
                                           { start_year: Date.today.year, end_year: Date.today.year + 7 },
                                           class: 'form-select date' %>
        </div>
      </div>

      <div class="row">
        <%= credit_card_form.label :cvv2, "CVV2", class: 'col-sm-2 col-form-label' %>
        <div class="col-sm-10">
          <%= credit_card_form.text_field :cvv2, class: 'form-control' %>
        </div>
      </div>
      <div class="mb-3 row justify-content-end">
        <div class="col-sm-10">
          <div class="form-text">
            Must be a 3-digit number
          </div>
        </div>
      </div>

    <% end %>
  </fieldset>

  <div class="mb-3">
    <%= form.submit "Create Order", class: "btn btn-warning" %>
  </div>
<% end %>

app/views/orders/new.html.erb
<h1>Place an Order</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to store", root_url, class: "btn btn-primary" %>
</div>

app/views/orders/show.html.erb
<h2>Order for <%= @order.user.email %></h2>

<div class="card mb-3">
  <div class="card-body">
    <h4 class="card-title">Order</h4>
      <%= render partial: 'shared/line_items', locals: { subject: @order, delete_links: false } %>

  </div>
</div>

<div class="card mb-3">
  <div class="card-body">
    <h4 class="card-title">Address</h4>

    <table class="table table-borderless">
      <tr>
        <th>Country</th>
        <td><%= @order.user.address.country %></td>
      <tr>
      <tr>
        <th>City</th>
        <td><%= @order.user.address.city %></td>
      <tr>
      <tr>
        <th>Line 1</th>
        <td><%= @order.user.address.line1 %></td>
      <tr>
      <tr>
        <th>Line 2</th>
        <td><%= @order.user.address.line2 %></td>
      <tr>
    </table>
  </div>
</div>

<div class="card mb-3">
  <div class="card-body">
    <h4 class="card-title">Credit Card</h4>

    <table class="table table-borderless">
      <tr>
        <th>Number</th>
        <td><%= @order.user.credit_card.number %></td>
      <tr>
      <tr>
        <th>Expiry Date</th>
        <td><%= @order.user.credit_card.expiry_date %></td>
      <tr>
      <tr>
        <th>CVV2</th>
        <td><%= @order.user.credit_card.cvv2 %></td>
      <tr>
    </table>
  </div>
</div>

<%= link_to "Back to Store", root_path, class: "btn btn-primary mb-4" %>